### ISSUE TITLE
Configure screen ratio?

### ISSUE THREAD

**Issue by garywill** [Bazmoc/Wii-Network-Config-Editor#1]
Hi @Bazmoc ,

This tool looks good! I have a Korean Wii with 4.3j semi-brick. Now I see the probabiliy to make it access the network.

Could you make a new similar tool to configure the screen ratio from 4:3 to 16:9 also?
Thanks ~~!

**Comment by Bazmoc** [comment]
Hi,

https://oscwii.org/library/app/Settings-Editor-GUI

This tool can change the aspect ratio. Feel free to reach out if you have more questions.
